# Generated by Django 2.1.4 on 2018-12-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='itinirary',
            new_name='itinerary',
        ),
    ]
