# Generated by Django 2.1.4 on 2018-12-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('id',)},
        ),
    ]
